# Generated by Django 5.0.7 on 2024-11-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pofolouser',
            name='main_field',
            field=models.CharField(choices=[('plan', 'plan'), ('design', 'design'), ('develop', 'develop')], default='plan', max_length=10),
        ),
        migrations.AlterModelTable(
            name='pofolouser',
            table='users',
        ),
    ]
