# Generated by Django 5.0.7 on 2024-12-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pofolouser',
            name='main_field',
            field=models.CharField(choices=[('기획', '기획'), ('디자인', '디자인'), ('개발', '개발')], default='기획', max_length=10),
        ),
    ]
