# Generated by Django 5.0.7 on 2024-12-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_pofolouser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pofolouser',
            name='profile_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
