# Generated by Django 5.0.7 on 2024-11-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_pofolouser_main_field_alter_pofolouser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pofolouser',
            name='profile_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
