# Generated by Django 5.0.7 on 2024-12-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='experiences',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.TextField(),
        ),
    ]
