# Generated by Django 5.0.7 on 2024-12-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='username',
            field=models.CharField(default='Unknown User', max_length=50),
        ),
    ]
