# Generated by Django 5.0.7 on 2024-12-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
