# Generated by Django 5.0.7 on 2024-11-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_skills_remove_project_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='picture_urls',
            new_name='project_img',
        ),
    ]
