# Generated by Django 5.0.7 on 2024-12-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
