# Generated by Django 5.0.7 on 2024-12-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_is_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryImage',
        ),
    ]
