# Generated by Django 5.0.7 on 2024-11-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_uploaded_at_temporaryimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.JSONField(default=list),
        ),
    ]
