# Generated by Django 5.0.7 on 2024-11-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.JSONField(default=list),
        ),
    ]
